### ISSUE TITLE
entrypoint script?

### ISSUE THREAD

**Issue by porjo** [daaku/goruntime#1]
How would I run an [entrypoint script](https://docs.docker.com/reference/builder/#entrypoint) from Dockerfile using `goruntime`?

When I try, I get error `exec: "/bin/sh": stat /bin/sh: no such file or directory`

**Comment by daaku** [comment]
You can't run entrypoint scripts because it doesn't include a shell. You'll need to use the `ENTRYPOINT ["/bin"]` syntax which doesn't need a shell.

**Comment by porjo** [comment]
Thanks. I ended up doing this instead: `CMD ["/usr/bin/busybox","ash","/entrypoint.sh"]`
